stages:
  - mavenbuild
  - maventest

maven-build:
  stage: mavenbuild     # one of the stages listed above
  tags:                 # to specify which runner to execute this job
    - nmorrow_tag        # change to your runner's tag
  script:               # what to execute for this job
    - cd Backend/CityWatcherBackend        # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn package       # maven package
  artifacts:            # where to output the packaged jar file, change 'Backend' to to where you have the pom.xml
    paths:
      - Backend/CityWatcherBackend/target/*.jar # change 'Backend' to where you have 'target' (do not add a / in the beginning)
  only:
    refs:
      - nmorrow_CICD            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/**/*    # more specifically - only when changes are made inside the 'Backend' folder

maven-test:
  stage: maventest     # one of the stages listed above
  tags:
    - nmorrow_tag   # change to your runner's tag
  script:
    - cd Backend/CityWatcherBackend       # change 'Backend' to to where you have the pom.xml (do not add / in the beginning)
    - mvn test         # maven test
  only:
    refs:
      - nmorrow_CICD            # only to trigger the pipeline when changes are pushed to 'main'
    changes:
      - Backend/**/*    # more specifically - only when changes are made inside the 'Backend' folder